### ISSUE TITLE
Multiple buttons submit

### ISSUE THREAD

**Issue by CripyIce** [Code-Forge-Net/remix-hook-form#10]
Hi there,
I made a form with a submit button which his handled with the default configurations.
Now, I want to add a delete button that will simply call a delete function on the server but I can't manage to do that.
Any ideas?

**Comment by AlemTuzlak** [comment]
@CripyIce should the button submit the form fields + a DELETE method or should it only submit to the endpoint with a DELETE method?

**Comment by CripyIce** [comment]
There is a submit button that is doing upsert and another button for delete only.
I managed to do what I need using
```js
<Button color="red" onClick={() => submit({}, { method: "delete" })}>
  Delete
</Button>
```
and then in `action` the following:
```ts
if (request.method === "DELETE") {
  await deletePost(_.toNumber(id), directoryId);
  return redirect(`/${directoryId}/blog`);
}
```

Is that the right way?

**Comment by AlemTuzlak** [comment]
> There is a submit button that is doing upsert and another button for delete only.
> I managed to do what I need using
> ```js
> <Button color="red" onClick={() => submit({}, { method: "delete" })}>
>   Delete
> </Button>
> ```
> and then in `action` the following:
> ```ts
> if (request.method === "DELETE") {
>   await deletePost(_.toNumber(id), directoryId);
>   return redirect(`/${directoryId}/blog`);
> }
> ```
> 
> Is that the right way?

Yes it is, you can also pass null to submit as first argument
