### ISSUE TITLE
Form always assumes the response from the action is an error.

### ISSUE THREAD

**Issue by jdpearce** [Code-Forge-Net/remix-hook-form#13]
Hi, we're using this in a fairly simple way, I think. Our action looks something like this:

```
export async function DoThingAction({ request }: ActionArgs) {
  const { errors, data } = await getValidatedFormData<DoThingForm>(
    request,
    zodResolver(DoThingForm)
  );
  if (errors) {
    return badRequest(
        result: 'error',
        error: errors.toString(),
      });
  }

  return json(await doThing(data));
}
```

The return type of `doThing` looks something like this:

```
export type doThingResponse = { result: 'success', someValue: string } | { result: 'error', error: string };
```

I don't think we're doing anything particularly unusual here but it seems that the `errors` property of `formState` in the component is _always_ being populated with the returned value of the action, so it always looks like there are errors.

Is there something unusual about how we've set up our action? (We don't want to have a separate success state component because it's feasible that folks will want to submit this form multiple times with more than one set of values)

**Comment by AlemTuzlak** [comment]
How the hook works under the hood it takes the returned action data from your useActionData hook and it checks if there is an errors field in the response, if there isn't it takes the whole action object and tries to match the structure of the returned data object, does this function response return an object that matches the original error object?

**Comment by nartc** [comment]
@AlemTuzlak I'm @jdpearce coworker and the shape of the response is `export type doThingResponse = { result: 'success', someValue: string } | { result: 'error', error: string };`. The data object that we're sending is `{ name: 'some name', id: 'some id' }` if this is what you meant by the "original error object"

**Comment by AlemTuzlak** [comment]
Interesting, mind providing a minimum repro so I can test it out and see what's going on?

**Comment by nartc** [comment]
@AlemTuzlak I'll try putting together something over the weekend, if not earlier next week

**Comment by jdpearce** [comment]
@AlemTuzlak Quick and dirty repro here -> https://github.com/jdpearce/rhf-action-error-repro

**Comment by AlemTuzlak** [comment]
@jdpearce I looked at the repro, I know what the issue is. You're right this is an issue. Will fix it as soon as I can!

**Comment by AlemTuzlak** [comment]
@jdpearce @nartc please try it now with 1.2 release, I tested it on your repro and fixed it

**Comment by Eianaftyio** [comment]
.patch
