### ISSUE TITLE
Warning: React has detected a change in the order of Hooks called by X

### ISSUE THREAD

**Issue by no-bs-js** [Code-Forge-Net/remix-hook-form#20]
I copy pasted the example from the README and added `fetcher` created by `useFetcher()`. Nothing else is changed, but when I submit form successfully I get that hooks were called in different order:

 
<img width="1431" alt="Screenshot 2023-08-18 at 16 23 55" src="https://github.com/Code-Forge-Net/remix-hook-form/assets/142565437/9d4746e8-b000-486f-a641-2f656211a6c3">

**Comment by AlemTuzlak** [comment]
@no-bs-js pushed a fix, can you please try with the latest version?

**Comment by no-bs-js** [comment]
Works fine, that was fast! Thanks!

**Comment by AlemTuzlak** [comment]
@no-bs-js awesome! no worries, thank you for the report!
