### ISSUE TITLE
Type 'string | FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by ivosabev** [Code-Forge-Net/remix-hook-form#21]
Here is another, again just copied from the README sample in a TypeScript file.

`{errors.name && <p>{errors.name.message}</p>}` gives two errors:

```
Type 'string | FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined' is not assignable to type 'ReactNode'.   Type 'FieldError' is not assignable to type 'ReactNode'.

Тype 'FieldError' is missing the following properties from type 'ReactPortal': key, children, props
```

`{errors.email && <p>{errors.email.message}</p>}` gives error:

```
Type 'string | FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined' is not assignable to type 'ReactNode'.
````

**Comment by AlemTuzlak** [comment]
@ivosabev if you do `errors.email?.message` ?

**Comment by ivosabev** [comment]
Nope. `.toString()` helps or the type guards given in this answer

https://stackoverflow.com/a/75931613/251555

**Comment by AlemTuzlak** [comment]
@ivosabev sorry for the late reponse, are you using this with chakra? From the issue you linked this seems to be an issue with react-hook-form and chakra not playing nice together? If so this problem has to be fixed upstream on that repo instead of here, I just reuse their types
