### ISSUE TITLE
`formState.isSubmitting` does not behave as we could expect

### ISSUE THREAD

**Issue by licarth** [Code-Forge-Net/remix-hook-form#22]
Hi,

I noticed that `formState.isSubmitting` is not working as expected. I tried to setup this library with Remix, implementing some slow action. 

### Actual behaviour
`isSubmitting` is set to `false` as soon as the POST network call is fired, before it returns.

### Expected behaviour
`isSubmitting` should stay `true` until action POST terminates.

### Reasons 

In `react-hook-form`, `formState.isSubmitting` is `true` as long as `onSubmit` promise is not either rejected or resolved, `onSubmit` being the argument of `handleSubmit`.

In `remix-hook-form`, users don't provide any `onSubmit` function as it's using the native implementation, triggering a Remix action.

In this repo, you're using Remix's `const submit = useSubmit()` hook to submit the form. But it does not seem to me that there is any way to listen to termination of that submit event (e.g. wait for the end of the POST request).

### Possible solution?

Actually, there is a debate [here](https://github.com/remix-run/remix/discussions/5023) about returning a promise for `useSubmit()` hook in react-router. They also give [a workaround](https://github.com/remix-run/remix/discussions/5023) that could work for us : to use `useActionData()` hook to know when the remix action is complete.

I guess we could do that to properly set `formState.isSubmitting, submitted, ...` etc.

```
let actionData = useActionData();
useEffect(() => {
    if (actionData.ok) {
       complete(actionData)
    }
}, [actionData]);
```

**Comment by AlemTuzlak** [comment]
@licarth Hmm that is a good point, there is a way to add this easily, because when you submit to an action the navigation state will be either submitting or redirecting until it is done so I can listen to that to find out if it's done, the native isSubmitting just waits for the valid data and submits. I will add this behavior to the package
