### ISSUE TITLE
Types getting inferred incorrectly with "moduleResolution: Bundler"

### ISSUE THREAD

**Issue by raulfdm** [Code-Forge-Net/remix-hook-form#29]
Hey folks. 👋

I'm trying to setup a new Remix app (v2 already) and it seems the new `tsconfig.json` is conflicting with how `remix-hook-form` is shipping types.

Now, Remix's`tsconfig.json` define something like this:

```jsonc
{
  // ... rest
  "compilerOptions": {
    // ... rest
    // NEW REMIX SETUP
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "target": "ES2022"
  }
}
```

And because of the module resolution got changed, I started getting 2 errors and I think they are related.

Here's what happens when I run `pnpm tsc`:

```
$ pnpm typecheck

> remix-hook-form-error@ typecheck /Users/raulmelo/development/personal/error-repos/remix-hook-form-error
> tsc

app/routes/_index.tsx:37:5 - error TS2345: Argument of type '{ mode: string; resolver: <TFieldValues extends FieldValues, TContext>(values: TFieldValues, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>; }' is not assignable to parameter of type 'UseRemixFormOptions<FieldValues$1>'.
  Object literal may only specify known properties, and 'mode' does not exist in type 'UseRemixFormOptions<FieldValues$1>'.

37     mode: "onSubmit",
       ~~~~

node_modules/.pnpm/remix-hook-form@2.0.1_@remix-run+react@2.0.1_react-dom@18.2.0_react-hook-form@7.46.2_react@18.2.0/node_modules/remix-hook-form/dist/index.d.ts:5:98 - error TS2307: Cannot find module 'react-hook-form/dist/types' or its corresponding type declarations.

5 import { FieldValues as FieldValues$1, UseFormProps, Path, RegisterOptions, UseFormReturn } from 'react-hook-form/dist/types';
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  app/routes/_index.tsx:37
     1  node_modules/.pnpm/remix-hook-form@2.0.1_@remix-run+react@2.0.1_react-dom@18.2.0_react-hook-form@7.46.2_react@18.2.0/node_modules/remix-hook-form/dist/index.d.ts:5
```

After some debuging, I noticed that's because `remix-hook-form` is importing the types from a path that "does not exists in the export" (which seems to be relevant when we have "bundler" mode set):

![image](https://github.com/Code-Forge-Net/remix-hook-form/assets/12464600/79699e72-8b70-48f0-9ac1-caa0e3ff80bb)

Fix I change it by removing the submodule:

```diff
-import { FieldValues as FieldValues$1, UseFormProps, Path, RegisterOptions, UseFormReturn } from 'react-hook-form/dist/types';
+import { FieldValues as FieldValues$1, UseFormProps, Path, RegisterOptions, UseFormReturn } from 'react-hook-form';
```

Everything seems to be working again:

![CleanShot 2023-09-26 at 13 23 12](https://github.com/Code-Forge-Net/remix-hook-form/assets/12464600/adfbc053-c56b-466a-9d01-dad3d3926cbc)

Not sure about the backwards compatibility of it though. I think some tests would be necessary.

## Reproduction

I've created a repository to help you to debug this problem: https://github.com/devraul/remix-v2-remix-hook-form-type-error

Or, you can simply:

1. create a brand-new remix project;
2. install `zod`, `remix-hook-form`, etc.;
3. setup the initial example you have in the README;
4. running `dev` and `build`, everything will just work;
5. run `pnpm typecheck` to see the error

## Tips

Also, there's 2 friendly suggestions regarding the type def:

1. For consistency, might be a good idea to define the `types` field in the export:
   ```diff
   "exports": {
       ".": {
         "import": "./dist/index.js",
         "require": "./dist/index.cjs",
   +     "types": "./dist/index.d.ts"
       }
     },
   ```
2. despite of that "typings" is "types" field equivalent, might be good to stick the one TS suggests at the docs snippet (`types`), just for consistency: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

---

Let me know if you need something else.

Cheers!

**Comment by AlemTuzlak** [comment]
@raulfdm Thank you so much for this investigation, I'll be fixing this ASAP, hopefully by EOW!

**Comment by AlemTuzlak** [comment]
@raulfdm Can you please install v2.0.2 and let me know if this fixes it, I've added some changes to the bundling process, should be good now

**Comment by kyle-lambert** [comment]
Can confirm v2.0.2 fixes this issue, cheers.

**Comment by AlemTuzlak** [comment]
awesome! closing as completed then!
