### ISSUE TITLE
Form states

### ISSUE THREAD

**Issue by CripyIce** [Code-Forge-Net/remix-hook-form#6]
Hi there,
A bit new to this library and `react-hook-form`.
How can I use the form states to show a loading and also a message when form is submitted successfully?
I saw all of `formState` available properties, but didn't manage to put it to work.
Thanks!!

**Comment by AlemTuzlak** [comment]
Hello @CripyIce, I am assuming you are using this library inside of Remix. The form submits directly to the server so the best way to keep track of your submission is by using this hook:
https://remix.run/docs/en/main/hooks/use-navigation
By checking if it is idle or not. Or if you're using a fetcher you can check the docs on how to handle a submission state there too.
If you have other questions feel free to ask!

**Comment by CripyIce** [comment]
Thanks @AlemTuzlak!
I managed by following the link you provided me.
